controllers/UsersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\user\User;
use app\models\user\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsersController implements the CRUD actions for User model.
 */
class UsersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout = "guest";

        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['site/index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionWhoIsOnline($id) {
        $returnData = User::find()
            ->where('last_seen >= ' . time() . '- 60')
            ->andWhere(['<>', 'id', $id])
            ->orderBy(['last_seen' => SORT_DESC])
            ->all();

        $response = Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_JSON;
        $response->data = $returnData;

        return $response;
    }

    public function actionWhoIsOffline($id) {
        $returnData = User::find()
            ->where('last_seen < ' . time() . '- 60')
            ->andWhere(['<>', 'id', $id])
            ->orderBy(['last_seen' => SORT_DESC])
            ->all();



        $response = Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_JSON;
        $response->data = $returnData;

        return $response;
    }

    public function actionStillAlive($id) {
        $user = $this->findModel($id);
        $time = time();
        $user->updateAttributes(['last_seen' => $time]);
        return true;
    }

    public function actionGetUserThread($id, $partner) {
        $returnData = ['someData' => 'I am data', 'someAnotherData' => 'I am another data'];

        $response = Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_JSON;
        $response->data = $returnData;

        return $response;
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/guest.php
<?php
use yii\helpers\Html;
use app\assets\CoreAsset;

/* @var $this \yii\web\View */
/* @var $content string */
/* @var $this->params['login'] string, @var $this->params['signup'] string
 * These variables are introduced manually to toggle "Active class" between login and signup
 * as per the page position. These values must be set in the views of login and signup actions */

CoreAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<!-- head -->
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<!-- /head -->

<!-- body -->

<body class="bg-primary">
<?php $this->beginBody() ?>

    <div class="cover"></div>

    <div class="overlay bg-primary">
        <!-- Begin flash messages if any -->
        <?php
        foreach (Yii::$app->session->getAllFlashes() as $key => $message) {
            echo '<div class="alert alert-'. $key .' text-center">' . $message . '</div>';
        }
        ?>
        <!-- End flash messages -->
    </div>

    <div class="center-wrapper">
        <div class="center-content">
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
                    <section class="panel bg-white no-b">
                        <ul class="switcher-dash-action">
                            <li class="<?= $this->params['login'] ?>"><a href="<?= Yii::$app->urlManager->createUrl('site/login') ?>" class="selected">Sign in</a></li>
                            <li class="<?= $this->params['signup'] ?>"><a href="<?= Yii::$app->urlManager->createUrl('users/create') ?>" class="">New account</a></li>
                        </ul>

                        <!-- View content is being passed inside the below div -->
                        <div class="p15">
                            <?= $content ?>
                        </div>


                    </section>
                    <p class="text-center">
                        Copyright &copy;
                        <span id="year" class="mr5"></span>
                        <a href="<?= Yii::$app->urlManager->createUrl('site/about') ?>">About Project FluxChat</a>
                    </p>
                </div>
            </div>

        </div>
    </div>
    <script type="text/javascript">
    var el = document.getElementById("year"),
        year = (new Date().getFullYear());
    el.innerHTML = year;
</script>
<?php $this->endBody() ?>
</body>
<!-- /body -->

</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use yii\helpers\Html;
use app\assets\CoreAsset;

/* @var $this \yii\web\View */
/* @var $content string */

CoreAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>

<!-- body -->

<body>
<?php $this->beginBody() ?>
<div class="app">
    <!-- top header -->
    <header class="header header-fixed navbar">

        <div class="brand" style="width: 300px; padding-left: 20px">
            <!-- toggle offscreen menu -->
            <a href="javascript:;" class="ti-menu off-left visible-xs" data-toggle="offscreen" data-move="ltr"></a>
            <!-- /toggle offscreen menu -->

            <!-- logo -->
            <a href="<?= Yii::getAlias('@web') ?>" class="navbar-brand">
                <img src="<?= Yii::getAlias('@web') ?>/img/logo.png" alt="">
                    <span class="heading-font">
                        ReachOut
                    </span>
            </a>
            <!-- /logo -->
        </div>

        <ul class="nav navbar-nav">
            <li class="header-search">
                <!-- toggle search -->
                <a href="javascript:;" class="toggle-search">
                    <i class="ti-search"></i>
                </a>
                <!-- /toggle search -->
                <div class="search-container">
                    <form role="search">
                        <input type="text" class="form-control search" placeholder="type and press enter">
                    </form>
                </div>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">

            <li class="hidden-xs">
                <a href="<?= Yii::$app->urlManager->createUrl('site/index') ?>">
                    <i class="ti-home"></i>
                </a>
            </li>
            <li>
                <a href="javascript:;" data-toggle="dropdown">
                    <i class="ti-info-alt"> </i>
                </a>
            </li>

            <li class="notifications dropdown">
                <a href="javascript:;" data-toggle="dropdown">
                    <i class="ti-bell"></i>
                    <div class="badge badge-top bg-danger animated flash">
                        <span>3</span>
                    </div>
                </a>
                <div class="dropdown-menu animated fadeInLeft">
                    <div class="panel panel-default no-m">
                        <div class="panel-heading small"><b>Notifications</b>
                        </div>
                        <ul class="list-group">
                            <li class="list-group-item">
                                <a href="javascript:;">
                                        <span class="pull-left mt5 mr15">
                                            <img src="<?= Yii::getAlias('@web') ?>/img/faceless.jpg" class="avatar avatar-sm img-circle" alt="">
                                        </span>
                                    <div class="m-body">
                                        <div class="">
                                            <small><b>CRYSTAL BROWN</b></small>
                                            <span class="label label-primary pull-right">New Message</span>
                                        </div>
                                        <span>Hey, how are you...</span>
                                        <span class="time small">2 mins ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="list-group-item">
                                <a href="javascript:;">
                                        <span class="pull-left mt5 mr15">
                                            <img src="<?= Yii::getAlias('@web') ?>/img/faceless.jpg" class="avatar avatar-sm img-circle" alt="">
                                        </span>
                                    <div class="m-body">
                                        <div class="">
                                            <small><b>Tim Cook</b></small>
                                            <span class="label label-primary pull-right">New Message</span>
                                        </div>
                                        <span>Good morning!</span>
                                        <span class="time small">8 mins ago</span>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
            <li class="off-right">
                <a href="javascript:;" data-toggle="dropdown">
                    <img src="<?= Yii::getAlias('@web') ?>/img/faceless.jpg" class="header-avatar img-circle" data-selfuser-name="<?= Yii::$app->user->identity->firstname ?> <?= Yii::$app->user->identity->lastname ?>" data-selfuser="<?= Yii::$app->user->identity->id ?>" data-alive-url="<?= Yii::$app->urlManager->createUrl('users/still-alive') ?>" alt="user" title="user">
                    <span class="hidden-xs ml10"><?= Yii::$app->user->identity->firstname ?></span>
                    <i class="ti-angle-down ti-caret hidden-xs"></i>
                </a>
                <ul class="dropdown-menu animated fadeInLeft">
                    <li>
                        <a href="javascript:;">Edit personal info</a>
                    </li>
                    <li>
                        <a href="javascript:;">
                            <div class="badge bg-danger pull-right">3</div>
                            <span>Notifications</span>
                        </a>
                    </li>
                    <li>
                        <a href="<?= Yii::$app->urlManager->createUrl('site/logout') ?>">Logout</a>
                    </li>
                </ul>
            </li>
        </ul>
    </header>
    <!-- /top header -->

    <section class="layout">
        <?= $content ?>


    </section>

</div>

<?php $this->endBody() ?>
</body>
<!-- /body -->

</html>
<?php $this->endPage() ?>