controllers/MessagesController.php
<?php

namespace app\controllers;

use app\models\UserThread;
use Yii;
use app\models\Message;
use app\models\MessageSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MessagesController implements the CRUD actions for Message model.
 */
class MessagesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Message models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MessageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Message model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Message model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Message();

        $content = $_POST['content'];
        $thread_id = $_POST['thread_id'];
        $author_id = $_POST['author_id'];
        $user2 = $_POST['user2'];

        if ($thread_id == 'none') {
            if (UserThread::findOne(['user1_id' => $author_id, 'user2_id' => $user2]) == null &&
                UserThread::findOne(['user1_id' => $user2, 'user2_id' => $author_id]) == null)
                $thread_id = $this->createThread($author_id, $user2);
        }

        $model->setAttributes([
            'content' => $content,
            'thread_id' => $thread_id,
            'author_id' => $author_id,
            'content_type' => 'text'
        ]);

        if($model->save())
            return $thread_id;
        else
            return "Failure";
    }

    /**
     * Updates an existing Message model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Message model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionGetUserThread($user1, $user2)
    {
        $thread = UserThread::findOne(['user1_id' => $user1, 'user2_id' => $user2]);
        if ($thread == null)
            $thread = UserThread::findOne(['user1_id' => $user2, 'user2_id' => $user1]);

        if($thread == null) {
            $thread_id = $this->createThread($user1, $user2);
            $returnData = ["thread_id" => $thread_id, "messages" => []];
        }
        else {
            $messages = Message::find()
                ->where(['thread_id' => $thread->id])
                ->orderBy('created_time')
                ->all();

            $returnData = ["thread_id" => $thread->id, "messages" => $messages];
        }

        $response = Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_JSON;
        $response->data = $returnData;

        return $returnData;
    }

    /**
     * Finds the Message model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Message the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Message::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function createThread($user1, $user2) {
        $thread = new UserThread();
        $thread->setAttributes(['user1_id' => $user1, 'user2_id' => $user2]);
        if ($thread->save())
            return $thread->id;
        else
            return 0;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\user\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'index'],
                'rules' => [
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['get', 'post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        $this->layout = 'guest';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionHello($message = "Hello")
    {
        return $this->render('hello', ['message' => $message]);
    }
}

controllers/UsersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\user\User;
use app\models\user\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsersController implements the CRUD actions for User model.
 */
class UsersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout = "guest";

        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['site/index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionWhoIsOnline($id) {
        $returnData = User::find()
            ->where('last_seen >= ' . time() . '- 60')
            ->andWhere(['<>', 'id', $id])
            ->orderBy(['last_seen' => SORT_DESC])
            ->all();

        $response = Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_JSON;
        $response->data = $returnData;

        return $response;
    }

    public function actionWhoIsOffline($id) {
        $returnData = User::find()
            ->where('last_seen < ' . time() . '- 60')
            ->andWhere(['<>', 'id', $id])
            ->orderBy(['last_seen' => SORT_DESC])
            ->all();



        $response = Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_JSON;
        $response->data = $returnData;

        return $response;
    }

    public function actionStillAlive($id) {
        $user = $this->findModel($id);
        $time = time();
        $user->updateAttributes(['last_seen' => $time]);
        return true;
    }

    public function actionGetUserThread($id, $partner) {
        $returnData = ['someData' => 'I am data', 'someAnotherData' => 'I am another data'];

        $response = Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_JSON;
        $response->data = $returnData;

        return $response;
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/hello.php
<?php
/**
 * Created by PhpStorm.
 * User: alwaysbollu
 * Date: 11/1/16
 * Time: 17:57
 */

use yii\helpers\Html;
?>
<?= Html::encode($message) ?>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\widgets\Breadcrumbs;

$this->title = 'Home - ReachOut';
?>
<!-- sidebar menu -->
<aside class="sidebar-300 offscreen-left bg-white">
    <div class="content-wrap">
        <div class="wrapper">
            <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 312px;">
                <div class="slimscroll" id="userspanel"
                     data-online-url="<?php echo Yii::$app->urlManager->createUrl('users/who-is-online') ?>"
                     data-offline-url="<?php echo Yii::$app->urlManager->createUrl('users/who-is-offline') ?>"
                     data-height="auto" data-size="6px" data-distance="0"
                     style="overflow: auto; width: auto; height: 312px;">
                    <div class="pt15 pl15 pr15 pb0 clearfix">
                        <h3 class="mt0">
                            <div class="pull-right"> <a class="small mr5" href="javascript:;"> <i
                                        class="ti-time text-primary"></i> </a> <a class="small" href="javascript:;"> <i
                                        class="ti-settings"></i> </a></div>
                            <span class="small"> <i class="ti-arrow-circle-up text-success"></i> <small>YOU'RE ONLINE
                                </small> </span></h3>
                    </div>
                    <div class="p15 text-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default btn-outline btn-sm">All Users</button>
                            <button type="button" class="btn btn-default btn-outline btn-sm">Online</button>
                        </div>
                    </div>
                    <div class="pt15 pl15 pr15 pb0">
                        <div class="h6 text-muted"><b>ONLINE</b></div>
                    </div>
                    <div id="online-users"></div>
                    <div class="pt15 pl15 pr15 pb0">
                        <div class="h6 text-muted"><b>OFFLINE</b></div>
                    </div>
                    <div id="offline-users"></div>

                </div>
                <div class="slimScrollBar"
                     style="background: rgb(0, 0, 0); width: 6px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 0px; height: 141.283px;"></div>
                <div class="slimScrollRail"
                     style="width: 6px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 0px;"></div>
            </div>
        </div>
    </div>
    <script type="application/javascript">
        $(document).ready(function () {
            var host = window.location.host;


        });
    </script>
</aside>
<!-- /sidebar menu -->
<!-- main content -->

<section class="main-content index-main">
    <div class="content-wrap">
        <div class="wrapper">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel overflow-hidden no-b profile p15" style="background: transparent">
                        <div class="row mb25">
                            <div class="col-sm-12">
                                <div class="row">
                                    <div class="col-xs-12 col-sm-6">
                                        <h4 class="mb0"><?= Yii::$app->user->identity->title ?></h4>
                                        <br>
                                        <ul class="user-meta">
                                            <li><i class="ti-email mr5"></i> <span><?= Yii::$app->user->identity->email ?></span></li>
                                            <li><i class="ti-settings mr5"></i> <a href="javascript:;">Edit Profile</a>
                                            </li>
                                        </ul>
                                        <br>
                                        <h4 class="mb0">About <b><?= Yii::$app->user->identity->firstname ?> <?= Yii::$app->user->identity->lastname ?></b></h4>
                                        <br>

                                        <p>Gary, a mere mortal man of 25. Likes skipping rope and playing with small fluffy cute
                                            toys. Enjoys the occasional UI/UX Design.</p>

                                    </div>
                                    <div class="col-xs-12 col-sm-6 text-center">
                                        <figure style="margin-top: 30px"><img src="/projectFluxChat/web/img/faceless.jpg" alt=""
                                                     class="avatar avatar-lg img-circle avatar-bordered" style="width: 200px">
                                            <br>
                                            <br>
                                            <h3 class="mb0"><?= Yii::$app->user->identity->firstname ?> <b><?= Yii::$app->user->identity->lastname ?></b></h3>
                                            <p style="margin-top: 5px"><?= Yii::$app->user->identity->email ?></p>
                                        </figure>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-6 mt25 text-center bt">
                                <div class="col-xs-12 col-sm-6"><h2 class="mb0"><b>89</b></h2>
                                    <small>Messages</small>
                                </div>
                                <div class="col-xs-12 col-sm-6"><h2 class="mb0"><b>7</b></h2>
                                    <small>Threads</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <section class="panel panel-default">
                        <header class="panel-heading">
                            <div class="pull-right"><a class="mr5" href="javascript:;"> <i class="ti-info-alt"></i> </a>
                                <a href="javascript:;"> <i class="ti-settings"></i> </a></div>
                            <span class="small text-uppercase"> Quick Chat </span></header>
                        <div class="panel-body no-p">
                            <div class="chat-user" style="display: inline-block;"><a href="javascript:;" class="user-avatar"> <img
                                        src="/projectFluxChat/web/img/faceless.jpg" class="avatar avatar-sm img-circle"
                                        alt="">

                                    <div class="status bg-danger"></div>
                                </a>

                                <div class="user-details"><p>Brandon Cruz</p>
                                    <small class="user-department">Human Resources</small>
                                </div>
                            </div>
                            <div class="chat-user" style="display: inline-block;"><a href="javascript:;" class="user-avatar"> <img
                                        src="/projectFluxChat/web/img/faceless.jpg" class="avatar avatar-sm img-circle"
                                        alt="">

                                    <div class="status bg-danger"></div>
                                </a>

                                <div class="user-details"><p>Brandon Cruz</p>
                                    <small class="user-department">Human Resources</small>
                                </div>
                            </div>
                            <div class="chat-user" style="display: inline-block;"><a href="javascript:;" class="user-avatar"> <img
                                        src="/projectFluxChat/web/img/faceless.jpg" class="avatar avatar-sm img-circle"
                                        alt="">

                                    <div class="status bg-danger"></div>
                                </a>

                                <div class="user-details"><p>Brandon Cruz</p>
                                    <small class="user-department">Human Resources</small>
                                </div>
                            </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
    <a class="exit-offscreen"></a></section>


<section class="main-content chatbox-holder" style="display:none">
    <div class="content-wrap">
        <div class="wrapper" style="bottom: 50px; padding: 20px 30px 0px 30px">
            <div class="chat-box" data-thread="none" data-partner="none"
                 data-thread-url="<?= Yii::$app->urlManager->createUrl('messages/get-user-thread') ?>">

            </div>
        </div>
    </div>
    <footer class="bt">
        <div class="form-input clearfix mt10 mb10">
            <div class="input-group"><input id="new-message" class="form-control input-sm"
                                            placeholder="Say Something ..."> <span
                    class="input-group-btn"> <button id="submit-message" class="btn btn-default btn-sm" type="button"
                                                     data-url="<?= Yii::$app->urlManager->createUrl('messages/create') ?>">
                        <i
                            class="ti-arrow-right"></i></button> </span></div>
        </div>
    </footer>
    <a class="exit-offscreen"></a></section>
<!-- /main content -->

<!-- Right side bar -->
<aside class="sidebar-300 offscreen-right">
    <div class="content-wrap">
        <div class="wrapper">
            <section class="panel no-b">
                <div class="panel-body"><a href="javascript:;" class="show text-center"> <img
                            src="/projectFluxChat/web/img/faceless.jpg" class="avatar avatar-lg img-circle" alt=""> </a>

                    <div class="show mt15 mb15 text-center">
                        <div class="h5"><b>Gerald Morris</b></div>
                        <p class="show text-muted">San Francisco, CA</p></div>
                </div>
                <div class="panel-footer no-p no-b">
                    <div class="row no-m">
                        <div class="col-xs-6 bg-primary p10 text-center brbl"><a href="javascript:;"> <span
                                    class="ti-comments show mb5"></span> 782 </a></div>
                        <div class="col-xs-6 bg-info p10 text-center"></div>

                    </div>
                </div>
            </section>
        </div>
    </div>
</aside>
<!-- /Right side bar -->

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model common\models\LoginForm */

$this->title = 'Login | ReachOut';

/* @var $this->params['login', 'signup'] - Manually introduced variables to toggle "Active class" between
 * login and Signup pages at layout.*/
$this->params = [
    'login' => 'active',
    'signup' => '',
];
?>
<!-- B - New Division -->

<?php $form = ActiveForm::begin([
    'id' => 'login-form',
    'layout' => 'default',
    'fieldConfig' => [
        'template' => '{input}<div class="help-block help-block-error main-login-help">{error}</div>',
    ],
]); ?>

<?= $form->field($model, 'email', [
    'inputOptions' => [
        'placeholder' => 'Enter Username',
        'class' => 'form-control input-lg mb25 mb25-scintin',
    ],
]) ?>

<?= $form->field($model, 'password', [
    'inputOptions' => [
        'placeholder' => 'Enter Password',
        'class' => 'form-control input-lg mb25 mb25-scintin',
    ],
])->passwordInput() ?>

<!--<div class="scintin-pull-right">-->
<!--    <a href="--><?//= Yii::$app->urlManager->createUrl('site/request-password-reset') ?><!--">Forgot password?</a>-->
<!--</div>-->

<div class="form-group">
    <?= Html::checkbox('LoginForm[rememberMe]',true); ?>
    <?= 'Remember me' ?>
</div>

<?= Html::submitButton('Login', [
    'class' => 'btn btn-primary btn-lg btn-block',
    'name' => 'login-button',
    'type' => 'submit',
]) ?>

<?php ActiveForm::end(); ?>